# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: pp's world tree Mk.III
email: pp2moonbird@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is pp's blog. My main focus is Data Analysis, Data visualization. I use Python, Qlikview, QlikSense and Tableau.
  I will also share games, animations, comic or other interesting stuff.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://pp2rollingstar.com" # the base hostname & protocol for your site
github_username:  pp2moonbird

# Build settings
markdown: kramdown
